apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u59wuzcim-go 
  janus-idp.io/tekton: u59wuzcim-go
  backstage.io/kubernetes-id: u59wuzcim-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u59wuzcim-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml